### ISSUE TITLE
Make CI better

### ISSUE THREAD

**Issue by leshow** [leshow/tokio-i3ipc#12]
Would be nice to have a CI that runs  rustfmt, clippy, cargo doc, and cargo test

**Comment by PurpleMyst** [comment]
I'm willing to work on this. Do you have any preference for GitHub Actions, Travis CI, CircleCI or anything else?

**Comment by leshow** [comment]
Awesome! What's the most popular among rust projects at the moment? I think
probably GitHub actions? I'd like to take the lead from projects like
Tokio, rustc, vector, just a few off the top of my head, if there are any
common conventions between them I'd like to do that.

This is a bit outside my usual comfort zone so I'm happy to hear suggestions

**Comment by PurpleMyst** [comment]
TravisCI is fine, and probably the most popular for Rust actually, so I'll work on adding what's requested to that
