### ISSUE TITLE
the `TransientFor` window property is an integer, not a string

### ISSUE THREAD

**Issue by nicklan** [leshow/tokio-i3ipc#3]
You have all window properties defined as strings here: https://github.com/leshow/tokio-i3ipc/blob/6abf3ab445d4206b883ae8767e2547cf25de249c/i3ipc-types/src/reply.rs#L57

However, sometimes the window properties json looks like:
```json
    "window_properties": {
      "class": "Alacritty",
      "instance": "Alacritty",
      "title": "user@user: /home/user/",
      "transient_for": 188743690
    },
```

Leading to errors of the form: 
`Error listening on i3 stream: invalid type: integer `188743690`, expected a string at line 1 column 647`

**Comment by leshow** [comment]
It must just be coincidence that I haven't run into this yet. Thanks for reporting!

**Comment by leshow** [comment]
Can you tell me what version of i3 you're running?

**Comment by nicklan** [comment]
Sure: i3 version 4.18.1 (2020-04-22)

**Comment by nicklan** [comment]
Here's a broken reply:
```json
{
  "change": "floating",
  "container": {
    "id": 94544255731616,
    "type": "con",
    "orientation": "none",
    "scratchpad_state": "none",
    "percent": 1,
    "urgent": false,
    "focused": false,
    "output": "eDP-1-1",
    "layout": "splith",
    "workspace_layout": "default",
    "last_split_layout": "splith",
    "border": "normal",
    "current_border_width": -1,
    "rect": {
      "x": 2142,
      "y": 996,
      "width": 882,
      "height": 152
    },
    "deco_rect": {
      "x": 0,
      "y": 0,
      "width": 882,
      "height": 26
    },
    "window_rect": {
      "x": 4,
      "y": 0,
      "width": 874,
      "height": 148
    },
    "geometry": {
      "x": 2142,
      "y": 996,
      "width": 874,
      "height": 148
    },
    "name": "name",
    "window": 100663361,
    "window_type": "splash",
    "window_properties": {
      "class": "[class]",
      "instance": "[instance]",
      "title": "[title]",
      "transient_for": 100663306
    },
    "nodes": [],
    "floating_nodes": [],
    "focus": [],
    "fullscreen_mode": 0,
    "sticky": false,
    "floating": "user_on",
    "swallows": []
  }
}
```

looks like `transient_for` is almost always `null`, but for floating splash windows it's not.

**Comment by leshow** [comment]
It took a bit of doing, because that's not exactly a uniform type. The fields aren't always there so serializing to a struct is difficult and it's not uniform enough to be a hashmap, I could've used an "untagged union" in serde but that would have forced users to do an extra unwrap operation. 

Anyway, I think what I've got now is workable and it passes your test case.

**Comment by leshow** [comment]
Pushed as `0.8` https://crates.io/crates/tokio-i3ipc

**Comment by nicklan** [comment]
awesome thanks, testing now

**Comment by leshow** [comment]
Feel free to re-open if you have any issues
