### ISSUE TITLE
Another deserialisation error

### ISSUE THREAD

**Issue by sersorrel** [leshow/tokio-i3ipc#41]
Calling `.unwrap()` on a `Result<Event>` from an `I3Stream::iter()` can fail:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: Error("invalid value: integer `-121`, expected usize", line: 1, column: 4025) }', src/main.rs:285:29
```

This seems a lot like #33, but it seems like that issue should have been fixed in the i3_ipc I have, so it's something else. I don't currently have the ability to investigate this further, sorry.

I'm using i3 version 4.20.1 and i3_ipc version 0.14.0.

**Comment by leshow** [comment]
It does look related. Perhaps we should just change all integers to isize or i64
