### ISSUE TITLE
Missing Node field: "current_border_width"

### ISSUE THREAD

**Issue by ohazi** [leshow/tokio-i3ipc#5]
Unless I missed it?

**Comment by leshow** [comment]
Looks like I may have missed it. I was working off of i3's docs and not all the fields available are there

**Comment by leshow** [comment]
what should the type of this field be? `usize`?

**Comment by ohazi** [comment]
> what should the type of this field be? `usize`?

@tmerr's implementation uses an i32:
https://github.com/tmerr/i3ipc-rs/blob/0a06e74d7a4ab448b081ce897e15c0cb273ba56d/src/reply.rs#L195-L196
```rust
    /// Number of pixels of the border width.
    pub current_border_width: i32,
```

i3 source seems to agree:
https://github.com/i3/i3/blob/9c2b8f8b31dda06a0bd01cab1f12cce41b3d1c13/include/data.h#L685
```C
    int current_border_width;
```

https://github.com/i3/i3/blob/f4964faef08d6add93afbd24cc00fef0c3f6c72a/src/ipc.c#L497-L498
```C
    ystr("current_border_width");
    y(integer, con->current_border_width);
```

I'm on a different computer now, so can't readily check, but I'm pretty sure I've seen `i3-msg -t get_tree` return -1 for the field in some cases, so I'm reasonably sure it should at least be signed.

**Comment by leshow** [comment]
Thanks for investigating, it kind of bothers me that it's not an `isize` at least but whatever, `i32` is fine

**Comment by ohazi** [comment]
Why `isize`? The `current_border_width` field is just the width (in DPI-adjusted pixels) of the decorative window border. Even with a crazy high DPI, I can't imagine ever needing more than `i8`. ¯\\\_(ツ)\_/¯

Anyway, it looks good from here. I have a toy project that's using @tmerr's `i3ipc` ([oi3h](https://github.com/ohazi/oi3h)), and I needed access to this field in order to try out your `i3_ipc`. I may not be ready to actually test it out for another few days.

**Comment by leshow** [comment]
`0.9.0` is released for all of the crates so you should be good now. Let me know if you have any other problems
